name: Deploy pythonanywhere webapp
on: [push]
jobs:
  deploy:
    environment:
      name: 'actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere API
        run: | 
          python ./.github/workflows/pythonanywhere.py ${{ secrets.USERNAME }} ${{ secrets.API_TOKEN }} www.pythonanywhere.com